### ISSUE TITLE
[feature request] - "Humanized" dataframes as responses

### ISSUE THREAD

**Issue by matheusmota** [AgrinessEdgeIoT/portiapy#6]
Portiapy's idea of providing dataframes as responses for summaries, selects and other tabular resultsets is pretty interesting. However, it is not human friendly, as we often have codes (for dimensions, things etc) and timestamps. How about supporting default transformations over columns of the dataframe?  (e.g., header_timestamp, thing_code, dimension_code, unity_code, timestamp)

Cheers

**Comment by LucasRGoes** [comment]
![Show!](https://media.tenor.com/images/485652e6fd0e36eb98604b0fb24450d9/tenor.gif)

**Comment by LucasRGoes** [comment]
Issue solved
